spring:
  datasource:
    #url: ${DB_URL}
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
    url: "jdbc:postgresql://postgres-service.default.svc.cluster.local:5432/k8sdb"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      leak-detection-threshold: 0
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      "[hibernate.hbm2ddl.jdbc_metadata_extraction_strategy]": individually

logging:
  level:
    "[com.zaxxer.hikari.pool.ProxyConnection]": ERROR

springdoc:
  api-docs:
    path: /api-docs       # 기본: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html  # 기본: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha